---
title: "Microarray"
author: " dandanpeng,LeaveLeaves,TaoDFang, orangelc1221, uraniumyo "
date: "2017-10-10"
output: html_document
---
## In-class exercise1: Summary

- Technique:Gene microarray technology rests on the ability to deposit many (tens of thousands) different DNA sequences on a small surface, usually a glass slide (often referred to as a ??chip??). 

- Principle: mRNA acts as a surrogate marker. Since mRNA is degraded easily, it is necessary to convert it into a more stable cDNA form. Labeling of cDNA is done by fluorochrome dyes Cy3 (green) and Cy5 (red). The principle behind microarrays is that complementary sequences will bind to each other.

- Application: antibiotic treatment, early detection of oral precancerous lesions, simultaneous testing of a large set of genetic samples during tumor formation.

### References
- [Microarray and its applications](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3467903/)
- [DNA microarrays: Types, Applications and their future](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4011503/)
- [How does a DNA microarray work?](https://www.youtube.com/watch?v=pWk_zBpKt_w)
- [Intorduction to microarray](http://www.premierbiosoft.com/tech_notes/microarray.html)

## In-class exercise2: Links

- Dup-Seq: sequencing ->radically lower the error rate of sequencing            ->Wilson score interval method
- GBS(Genotyping by Sequencing) -> Illumina Sequencing -> MLM (Mixed Linear Model)
